var members = [
    {
        name:"小郑",
        job:"室长",
        introduction:[
            "悦动工作室室长"
        ],
        sign:"",
        id:1,
        picture:"../Picture/member_1.webp",
        contact: [
            'QQ号：2236933051',
            '邮箱：2236933051@qq.com'
        ]
    },
    {
        name:"反性能老魔",
        job:"副室长",
        introduction:[
            "会Python，javascript和一点点css",
            "据说他的电脑用的是3代i5……"
        ],
        sign:"键盘总得敲到废，代码写到人疲累！",
        id:2,
        picture:"../Picture/member_5.webp",
        contact: [
            'QQ号：3171244185',
            '邮箱：3171244185@qq.com'
        ]
    },
    {
        name:"超级苦力怕1324",
        job:"程序组长",
        introduction:[
            "会python和html,css,JavaScript",
            "懂得安卓，windows软件和网站开发"
        ],
        sign:"",
        id:3,
        picture:"../Picture/member_2.webp",
        contact: [
            'QQ号：2672066839',
            '邮箱：2672066839@qq.com'
        ]
    },
    {
        name:"普通的编程萌新",
        job:"程序组",
        introduction:[
            "一个普通到不能再普通的编程萌新",
            "会Python，还会一点JavaScript、和C语言"
        ],
        sign:"",
        id:4,
        picture:"../Picture/member_4.webp",
        contact: [
            'QQ号：2100400850',
            '邮箱：2100400850@qq.com'
        ]
    }
];